- _information-for-borrowers/0-guide-to-borrowing-from-licensed-moneylenders-english.md
Rectification of title to "FAQs on Borrowing from Licensed Moneylenders"
> Rectification of title to "FAQs on Borrowing from Licensed Moneylenders"

- _information-for-borrowers/2-list-of-licensed-moneylenders-in-singapore.md
Updated ML List as at 1 Jan 2020
> Updated ML List as at 1 Jan 2020

- _information-for-borrowers/0-guide-to-borrowing-from-licensed-moneylenders-english.md
Added Qns 11 for FAQ for borrowers
> Added Qns 11 for FAQ for borrowers

- _information-for-borrowers/0-guide-to-borrowing-from-licensed-moneylenders-english.md
> Amended formatting of Qns 11

- _information-for-borrowers/2-list-of-licensed-moneylenders-in-singapore.md
Updated & formatted scam advisory
> Updated & formatted scam advisory

- _information-for-borrowers/2-list-of-licensed-moneylenders-in-singapore.md
Updated list of ML as at 1 Feb 2020 on webpage
> Updated list of ML as at 1 Feb 2020 on webpage

- _information-for-moneylenders/0-information-for-licensed-moneylenders.md
- _information-for-moneylenders/7-SkillsFuture Fellowships and SkillsFuture Employer Award 2022
> Amending titles

- _information-for-moneylenders/7-SkillsFuture Fellowships and SkillsFuture Employer Award 2022
> Update 7-SkillsFuture Fellowships and SkillsFuture Employer Award 2022

- _information-for-moneylenders/information-for-licensed-moneylenders.md
Updating relevent sections on webpage due to the changes in MLA
> Updating relevent sections on webpage due to the changes in MLA 

- _information-for-moneylenders/forms.md
remove Annex for application to employ/engage persons
> remove Annex for application to employ/engage persons

- _information-for-borrowers/list-of-licensed-moneylenders-in-singapore.md
Update ML List as at 1 May 2022 on web
> Update ML List as at 1 May 2022 on web

- _information-for-moneylenders/forms.md
Update BG form on ROM Web link
> Update BG form on ROM Web link

- _information-for-borrowers/list-of-licensed-moneylenders-in-singapore.md
Updating ML list as at 1 Jun 2022 on webpage
> Updating ML list as at 1 Jun 2022 on webpage

- _information-for-borrowers/list-of-licensed-moneylenders-in-singapore.md
Update file: list-of-licensed-moneylenders-in-singapore as at 1 Jul 2022.
> Update file: list-of-licensed-moneylenders-in-singapore.md

- _information-for-borrowers/List of Exempt Moneylenders.md
- _information-for-borrowers/collection.yml
Create page: List of exempt moneylenders
> Create page: List of exempt moneylenders

- _information-for-borrowers/list-of-licensed-moneylenders-in-singapore.md
Updating of ML Listing on ROM's webpage
> Updating of ML Listing on ROM's webpage

- _information-for-borrowers/List of Exempt Moneylenders.md
Update list of COE holders as at 1 Sep 2022
> Update list of COE holders as at 1 Sep 2022

- _information-for-borrowers/list-of-licensed-moneylenders-in-singapore.md
amending advisory under list of LMLs
> amending advisory under list of LMLs

- _information-for-borrowers/List of Exempt Moneylenders.md
Updating list of COE holders on webpage
> Updating list of COE holders on webpage

- _information-for-borrowers/list-of-licensed-moneylenders-in-singapore.md
Updating list of moneylenders as at 1 Oct 2022 on webpage
> Updating list of moneylenders as at 1 Oct 2022 on webpage

- _information-for-moneylenders/aml-cft-newsletters.md
Update AMLCFT Newsletter Issue 1 of 2022 on Website
> Update AMLCFT Newsletter Issue 1 of 2022 on Website

- _information-for-moneylenders/information-for-licensed-moneylenders.md
Adding revision clause to ML test on webpage
> Adding revision clause to ML test on webpage

- _information-for-moneylenders/information-for-licensed-moneylenders.md
Revising information on test fess on webpage
> Revising information on test fess on webpage

- _information-for-borrowers/List of Exempt Moneylenders.md
Updating permalink address for page
> Updating permalink address for page

- _information-for-moneylenders/information-for-licensed-moneylenders.md
Updating Information for Licensees
> Updating Information for Licensees

- _information-for-borrowers/faqs-on-borrowing-from-licensed-moneylenders.md
- _information-for-borrowers/list-of-licensed-moneylenders-in-singapore.md
Addition of local charges to 1800 number
> Addition of local charges to 1800 number

- _information-for-borrowers/faqs-on-borrowing-from-licensed-moneylenders.md
Updating address for Adullam Life Counselling
> Updating address for Adullam Life Counselling

- _information-for-moneylenders/Compliance (AML | CFT | CPF).md
Fixed broken link for "Countering Proliferation Financing Industry Best Practice Paper"
> Fix broken link

- _information-for-borrowers/faqs-on-borrowing-from-licensed-moneylenders.md
Updating Q10 of Information for borrowers
> Updating Q10 of Information for borrowers

- index.md
> Amending link in banner

- pages/terms-of-use.md
Updating links for privacy statement
> Updating links for privacy statement

- _data/footer.yml
> Updating FAQ link
